### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by dnakamashi** [catdad-experiments/libheif-js#25] opened 2024-04-23 10:45 UTC
Hey, first of all, thanks for building and open sourcing this lib.

I'm trying to use it in my react application bundling it with Webpack and I'm getting this error. Do you know what can it be?

```
Compiled with problems:X

WARNING in ./node_modules/libheif-js/libheif-wasm/libheif-bundle.js 1:235-242

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted


WARNING in ./node_modules/libheif-js/libheif-wasm/libheif-bundle.js 1:364-371

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by jocluzet** [comment] 2024-05-13 12:30
same issue for me...

**Comment by catdad** [comment] 2024-05-14 03:44
This appears to be a duplicate of #23

**Closed by catdad** 2024-05-14 03:44 UTC
Labels: duplicate
